# Dockerfile.dev

# Use uma imagem base do Node.js (versão LTS mais recente é uma boa escolha)
FROM node:lts-alpine as development

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie o package.json e o package-lock.json (ou yarn.lock) para o diretório de trabalho
# Isso aproveita o cache de camadas do Docker, para não reinstalar dependências a cada build se não houver mudanças nesses arquivos
COPY package.json ./
# Se você usar yarn, descomente a linha abaixo e comente a de cima
# COPY package.json yarn.lock ./

# Instale as dependências do projeto
RUN npm install
# Se você usar yarn, descomente a linha abaixo e comente a de cima
# RUN yarn install

# Copie o restante dos arquivos do projeto para o diretório de trabalho
COPY . .

# Exponha a porta que o Vite usa para o servidor de desenvolvimento (definida em vite.config.ts)
EXPOSE 5002

# Comando para iniciar o servidor de desenvolvimento Vite
# O --host garante que o servidor Vite seja acessível de fora do container
CMD ["npm", "run", "dev", "--", "--host"]
